### PR TITLE
fixed tokenizers package conflicting

### PR DESCRIPTION
**Pull request by wannaphong**
I fixed tokenizers package conflicting. #28

Notebook for test (all work): https://colab.research.google.com/drive/1V_4mFjHzTCVPi2-JYOHrzAzu9-URvVi1?usp=sharing

### CODE REVIEW

**Comment by cstorm125** [comment]
Will this break the experiment scripts? 
@artificiala @zincorca

**Comment by artificiala** [comment]
> Will this break the experiment scripts?
> @artificiala @zincorca

In our experiment, we use `tokenizers==0.9.2` for `wanchanberta-base-wiki-*` and `tokenizers==0.9.3` for  `wanchanberta-base-att-spm-uncased`. I think that by changing the version from 0.9.4 -> 0.9.3 will not break the experiment scripts.

**Comment by artificiala** [comment]
However, by changing the version of transformers from 3.5.1 to 4.x , it is required to refactor the scripts under `./thai2transformers` according the the breaking changes described in https://github.com/huggingface/transformers/releases/tag/v4.0.0.

**Comment by artificiala** [comment]
Hello @wannaphong,

I would like to thank for the patch that solve the package conflicting issue. However, with this change, it will break the existing code base (as there are breaking changes for the major release [4.x](https://github.com/huggingface/transformers/releases/tag/v4.0.0.). In my opinion, to ensure reproducibility, changing the version of `tokenizers` would be safer.

Refactoring the codebase and testing the model training/finetuning scripts in order to make them compatible the new major release of `transformers` will be listed in the backlog.

**Pull request closed without merging**
